version: 2
updates:
  - package-ecosystem: npm
    directory: /.circleci/config
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /default_app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /npm
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/app-path
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/command-line
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/context-bridge/context-bridge-mutability
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/cookie-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/default-menu
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/exit-closes-all-windows-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/first-party-sets/base
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/first-party-sets/command-line
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/ipc-main-listeners
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/locale-check
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/mixed-sandbox-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/net-log
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/quit-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/relaunch
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/safe-storage/decrypt-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/safe-storage/encrypt-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/singleton-data
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/singleton-userdata
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/singleton
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/test-menu-null
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/test-menu-visibility
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/utility-process/env-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/utility-process/inherit-stderr
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/utility-process/inherit-stdout
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/api/window-all-closed
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/apps/crash
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/apps/open-new-window-from-link
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/apps/remote-control
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/apps/self-module-paths
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/apps/set-path
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/apps/xwindow-icon
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/auto-update/check-with-headers
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/auto-update/check
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/auto-update/initial
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/auto-update/update-json
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/auto-update/update
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/native-addon/echo
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/native-addon/uv-dlopen
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec/fixtures/snapshot-items-available
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /spec
    schedule:
      interval: daily
