# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
version: "{build}"

init:
  - git config --global core.autocrlf input

platform:
  - x86
  - x64

install:
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - cmd: python script/cibuild

# disable build and test pahses
build: off
test: off
