version: 1.0.{build}
build_cloud: libcc-20
image: libcc-20-vs2017-15.7.4
environment:
  GIT_CACHE_PATH: C:\Users\electron\libcc_cache
  DISABLE_CRASH_REPORTER_TESTS: true
  ELECTRON_OUT_DIR: Default
build_script:
  - ps: >-
      if(($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME -split "/")[0] -eq ($env:APPVEYOR_REPO_NAME -split "/")[0]) {
        Write-warning "Skipping PR build for branch"; Exit-AppveyorBuild
      }
  - echo "Building $env:GN_CONFIG build"
  - git config --global core.longpaths true
  - cd ..
  - md src
  - ps: Move-Item $env:APPVEYOR_BUILD_FOLDER -Destination src\electron
  - ps: $env:CHROMIUM_BUILDTOOLS_PATH="$pwd\src\buildtools"
  - ps: $env:SCCACHE_PATH="$pwd\src\electron\external_binaries\sccache.exe"
  - >-
      gclient config
      --name "src\electron"
      --unmanaged
      "https://github.com/electron/electron"
  - gclient sync --with_branch_heads --with_tags
  - cd src
  - gn gen out/Default "--args=import(\"//electron/build/args/%GN_CONFIG%.gn\") %GN_EXTRA_ARGS%"
  - ninja -C out/Default electron:electron_app
  - gn gen out/ffmpeg "--args=import(\"//electron/build/args/ffmpeg.gn\") %GN_EXTRA_ARGS%"
  - ninja -C out/ffmpeg electron:electron_ffmpeg_zip
  - ninja -C out/Default electron:electron_dist_zip
  - ninja -C out/Default electron:electron_mksnapshot_zip
  - ninja -C out/Default electron:electron_chromedriver_zip
  - ninja -C out/Default third_party/electron_node:headers
  - appveyor PushArtifact out/Default/dist.zip
  - appveyor PushArtifact out/Default/chromedriver.zip

  - appveyor PushArtifact out/ffmpeg/ffmpeg.zip
  - ps: >-
      if ($env:GN_CONFIG -eq 'release') {
        ninja -C out/Default third_party/breakpad:dump_syms
      }
  - if "%GN_CONFIG%"=="release" ( python electron\script\dump-symbols.py -d %cd%\out\Default\electron.breakpad.syms -v)
  - ps: >-
      if ($env:GN_CONFIG -eq 'release') {
        python electron\script\zip-symbols.py
        appveyor PushArtifact out/Default/symbols.zip
      }
test_script:
  - if "%GN_CONFIG%"=="testing" ( echo Verifying non proprietary ffmpeg & python electron\script\verify-ffmpeg.py --build-dir out\Default --source-root %cd% --ffmpeg-path out\ffmpeg )
  - ps: >-
      if ($env:GN_CONFIG -eq 'testing') {
        New-Item .\out\Default\gen\node_headers\Release -Type directory
        Copy-Item -path .\out\Default\electron.lib -destination .\out\Default\gen\node_headers\Release\node.lib
      } else {
        echo "Skipping tests for $env:GN_CONFIG build"
      }
  - cd electron
  - if "%GN_CONFIG%"=="testing" ( echo Running test suite & npm run test -- --ci )
  - cd ..
deploy_script:
  - cd electron
  - ps: >-
      if (Test-Path Env:\ELECTRON_RELEASE) {
        if (Test-Path Env:\UPLOAD_TO_S3) {
          Write-Output "Uploading Electron release distribution to s3"
          & python script\upload.py --upload_to_s3
        } else {
          Write-Output "Uploading Electron release distribution to github releases"
          & python script\upload.py
        }
      }
