name: Clean Source Cache

# Description:
# This workflow cleans up the source cache on the cross-instance cache volume
# to free up space. It runs daily at midnight and clears files older than 15 days.

on:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  clean-src-cache:
    if: github.repository == 'electron/electron'
    runs-on: electron-arc-centralus-linux-amd64-32core
    permissions:
      contents: read
    container:
      image: ghcr.io/electron/build:bc2f48b2415a670de18d13605b1cf0eb5fdbaae1
      options: --user root
      volumes:
        - /mnt/cross-instance-cache:/mnt/cross-instance-cache
        - /mnt/win-cache:/mnt/win-cache
    steps:
    - name: Cleanup Source Cache
      shell: bash
      run: |
        df -h /mnt/cross-instance-cache
        find /mnt/cross-instance-cache -type f -mtime +15 -delete
        df -h /mnt/cross-instance-cache
        df -h /mnt/win-cache
        find /mnt/win-cache -type f -mtime +15 -delete
        df -h /mnt/win-cache
