name: Issue Transferred

on:
  issues:
    types: [transferred]

permissions: {}

jobs:
  issue-transferred:
    name: Issue Transferred
    runs-on: ubuntu-latest
    permissions: {}
    if: ${{ !github.event.changes.new_repository.private }}
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@e14e47722ed120360649d0789e25b9baece12725 # v2.0.0
        id: generate-token
        with:
          creds: ${{ secrets.ISSUE_TRIAGE_GH_APP_CREDS }}
          org: electron
      - name: Remove from issue triage
        uses: dsanders11/project-actions/delete-item@2134fe7cc71c58b7ae259c82a8e63c6058255678 # v1.7.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          project-number: 90
          item: ${{ github.event.changes.new_issue.html_url }}
          fail-if-item-not-found: false
